### PR TITLE
timer: rethink start and end times

### PR DESCRIPTION
**Pull request by oscfdezdz**
Start time counts from the first time the start button is clicked and will not restart if paused and resumed.

End time would be the instant the user clicks the stop button.

Closes https://github.com/lainsce/khronos/issues/106

Hopefully code explains better! I don't know if this is the way other apps with the same purpose behave, but it's what makes sense to me 😄

### CODE REVIEW

**Comment by lainsce** [comment]
What I think is missing is "When I wanna stop a log's timer completely, thus acting towards the objective of I don't want to add to a log's timer."

**Comment by oscfdezdz** [comment]
I'm not sure I'm following along 😅 
Is it possible to reset the timer in latest stable version without closing the window or adding it to a log?

**Comment by lainsce** [comment]
> I'm not sure I'm following along sweat_smile Is it possible to reset the timer in latest stable version without closing the window or adding it to a log?

The thing is, the pause button will make it look like the button isn't for stopping completely the timer, and yes for pausing to resume later for the user.

Maybe something else could be done to make the task resumable that is more intuitive..

**Comment by lainsce** [comment]
With the UI changes, and this PR, I think everything is in place.

**Pull request merged**
