### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by lainsce** [comment]
Oh, I'd like if you could do this for the Khronos Next PR instead. Master branch is frozen for that PR.
But, I need to update the po files first, and I can only do that soon as my main pc's status is back to working.

I'll mention you when I updated the po files.

**Comment by lainsce** [comment]
@Vistaus It's ready, target the other PR for translations ok? Closing...

**Comment by Vistaus** [comment]
Sorry for not replying earlier. I will absolutely target that other PR. What is the best approach for that (i.e. how do I target that PR in the most clean way?)

**Comment by lainsce** [comment]
On your fork, move to the branch in question with `git checkout -b translation-dutch khronos-next`, then, you do things like always and push to that and make a PR off of that.

**Pull request closed without merging**
